version: '3'

networks:
  app:
    driver: bridge

services:
  app:
    build:
      context: ./docker/app
    networks:
      - app
    volumes:
      - '.:/var/www'

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - ${APP_PORT:-80}:80
    networks:
      - app
    volumes:
      - './public:/var/www/public'

